#!/usr/bin/env bash
# Install git pre-commit hooks that call scripts/doc-audit.sh on .md changes.
#
# Designed for multi-module repos where the top-level directory is NOT a
# git repo and each module has its own .git. Also works for single-repo
# projects (edit MODULES list below).
#
# Usage:
#   bash scripts/install-hooks.sh              # install to modules in MODULES list
#   bash scripts/install-hooks.sh --auto       # auto-detect submodule git repos
#   bash scripts/install-hooks.sh --dry        # preview without writing
#   bash scripts/install-hooks.sh --uninstall  # revert core.hooksPath on each module
#
# After install: each module's `.githooks/pre-commit` fires when you commit
# a .md change; it delegates to the top-level `scripts/doc-audit.sh`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$REPO_ROOT"

# -----------------------------------------------------------------------------
# Customize these for your project:
# -----------------------------------------------------------------------------
# Modules that get the hook by default. Each must be a direct/nested dir with
# its own `.git` directory.
MODULES=(
    # "my-module-a"
    # "my-module-b"
    # "subdir/my-module-c"
)
# -----------------------------------------------------------------------------

AUTO_DETECT=0
DRY_RUN=0
UNINSTALL=0
for arg in "$@"; do
    case "$arg" in
        --auto) AUTO_DETECT=1 ;;
        --dry) DRY_RUN=1 ;;
        --uninstall) UNINSTALL=1 ;;
        -h|--help)
            grep '^#' "$0" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) echo "Unknown arg: $arg" >&2; exit 2 ;;
    esac
done

# Auto-detect: find all `.git` directories up to depth 4 under REPO_ROOT
if [[ $AUTO_DETECT -eq 1 ]]; then
    MODULES=()
    while IFS= read -r git_dir; do
        mod_dir="$(dirname "$git_dir")"
        # Strip absolute prefix to get repo-relative path
        rel="${mod_dir#$REPO_ROOT/}"
        # Skip if no strip happened (means it's the root itself)
        [[ "$rel" == "$mod_dir" ]] && continue
        MODULES+=("$rel")
    done < <(find "$REPO_ROOT" -maxdepth 4 -type d -name ".git" 2>/dev/null | sort)
    echo "Auto-detected ${#MODULES[@]} module(s) with .git"
fi

if [[ ${#MODULES[@]} -eq 0 && $UNINSTALL -eq 0 ]]; then
    echo "⚠️  MODULES list is empty. Edit scripts/install-hooks.sh or use --auto" >&2
    exit 2
fi

# -----------------------------------------------------------------------------
# pre-commit hook content (written into each module's .githooks/pre-commit)
# -----------------------------------------------------------------------------
HOOK_CONTENT='#!/usr/bin/env bash
# Generated by install-hooks.sh — do not edit by hand; re-run the installer.
#
# Fires on git commit when staged .md files are present. Walks up from the
# module root to find the repo containing scripts/doc-audit.sh and delegates.

set -uo pipefail

MODULE_ROOT="$(git rev-parse --show-toplevel)"
ROOT="$(dirname "$MODULE_ROOT")"
# Walk up a few levels in case the module is nested (e.g. keycloak-spi/foo/)
for _ in 1 2 3; do
    if [[ -f "$ROOT/scripts/doc-audit.sh" ]]; then
        break
    fi
    ROOT="$(dirname "$ROOT")"
done

if [[ ! -f "$ROOT/scripts/doc-audit.sh" ]]; then
    echo "⚠️  doc-audit.sh not found upstream of $MODULE_ROOT — skipping drift check" >&2
    exit 0
fi

staged_md=$(git diff --cached --name-only --diff-filter=ACMR | grep -E "\\.md$" || true)
if [[ -z "$staged_md" ]]; then
    exit 0
fi

echo "🔍 Documentation change detected, running doc-garden drift check..."
bash "$ROOT/scripts/doc-audit.sh"
'

# -----------------------------------------------------------------------------
# Uninstall mode
# -----------------------------------------------------------------------------
if [[ $UNINSTALL -eq 1 ]]; then
    echo "===== Uninstall pre-commit hooks ====="
    # Uninstall auto-detects from .githooks existence
    while IFS= read -r hook; do
        mod="$(dirname "$(dirname "$hook")")"
        rel="${mod#$REPO_ROOT/}"
        (cd "$mod" && git config --unset core.hooksPath 2>/dev/null || true)
        rm -f "$hook"
        rmdir "$mod/.githooks" 2>/dev/null || true
        printf "%-50s %s\n" "$rel" "↩ removed"
    done < <(find . -maxdepth 5 -path '*/.githooks/pre-commit' 2>/dev/null)
    exit 0
fi

# -----------------------------------------------------------------------------
# Install / dry-run
# -----------------------------------------------------------------------------
LABEL=$( [[ $DRY_RUN -eq 1 ]] && echo "dry-run" || echo "install" )
[[ $AUTO_DETECT -eq 1 ]] && LABEL="$LABEL + auto-detected"
echo "===== Install pre-commit hooks ($LABEL) ====="
INSTALLED=0
SKIPPED=0
for mod in "${MODULES[@]}"; do
    if [[ ! -d "$mod/.git" ]]; then
        printf "%-50s %s\n" "$mod" "⚠️  not a git repo, skipped"
        SKIPPED=$((SKIPPED + 1))
        continue
    fi

    HOOK_DIR="$mod/.githooks"
    HOOK_FILE="$HOOK_DIR/pre-commit"

    if [[ $DRY_RUN -eq 1 ]]; then
        printf "%-50s %s\n" "$mod" "[would install → $HOOK_FILE]"
    else
        mkdir -p "$HOOK_DIR"
        printf '%s' "$HOOK_CONTENT" > "$HOOK_FILE"
        chmod +x "$HOOK_FILE"
        (cd "$mod" && git config core.hooksPath .githooks)
        printf "%-50s %s\n" "$mod" "✅ installed"
    fi
    INSTALLED=$((INSTALLED + 1))
done

echo ""
echo "===== Summary ====="
echo "Installed: $INSTALLED"
echo "Skipped:   $SKIPPED"
if [[ $DRY_RUN -eq 0 && $INSTALLED -gt 0 ]]; then
    echo ""
    echo "Next commit with a .md change in any installed module will trigger doc-audit.sh"
    echo "Uninstall: bash scripts/install-hooks.sh --uninstall"
fi
